apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: go-waylonwalker-com

resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: waylonwalker-com

images:
  - name: ghcr.io/waylonwalker/markata-go
    newTag: latest
