---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: webmention-io
  namespace: go-waylonwalker-com
spec:
  encryptedData:
    WEBMENTION_IO_TOKEN: AgAiK5aZDkaqqZRE4qkih9AHGqvkcq6XijD7QxVFDARv5d2rjApB7T/2I4tSvgb9s0mEjEPcwMKC7QXuesiETNxvDVViPten1oUYhURibJ+ram5C1OjkV/dRQJ+Gwe2Q+/bpLXAE/5OJJNAm7C5worfhEU1AAyas9E7etbizlzqesfeWe8Hrt1npK0uw6WSy0uLAYdc321/NFAeH3DcXxEZabYyq1ajeiFXNQh5dnHfcFvzFTF0ATfoKHao7csiaJelyWuupogijBAeIFlm3OYmIZt6GTIAJicHrO7yb1YDbVkq4MaPiQ0W7/juzOZ01FiP57bj4OIHXbVoCgN/OB764PRcCjPobkfJYYfRsq0k/cDxfhtKulDTLdeTHMaxKEa/j/81Fl+cvRx75PzDcRhLXvDPhYQX6uxXGAGdSOYcl0U7nvQidUiUqTLdr9bI5TgWQpWNwaQVM1WaKkTeakLS0LbDDv8fEZoC9Iz/+kt3oHToHoIENcrqLUlJjjJMZsDE2oQgVH5yD1u33YEQTODAt9U+IDI+35cYNeL7t53uSEOo9usDHmarR0ac0XMWApuBB+u6uRxBPB98sklFUmjtbWLAQtF7PRqfp1+0UeFGnY4gnXn/kQr7KkLjLtVyKzpnSETvl/s3pCNfqbytnEH/i2Hy/ApW9c4MRn1uDW9vEHF248oWjfmUlPp55OpY3JMSHlwxGyfXH88l5xk3PnG+fFPKkzSl+
  template:
    metadata:
      name: webmention-io
      namespace: go-waylonwalker-com
